source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VOKEmbeddedTemplateTools_Example', :exclusive => true do
  pod "VOKEmbeddedTemplateTools", :path => "../"
end

target 'VOKEmbeddedTemplateTools_Tests', :exclusive => true do
  pod "VOKEmbeddedTemplateTools", :path => "../"

  
end
