source 'https://github.com/CocoaPods/Specs.git'

target 'VOKEmbeddedTemplateTools', :exclusive => true do
  pod "VOKEmbeddedTemplateTools", :path => "../"
  pod 'zipzap', '8.0.3'  # 8.0.4 won't compile :( https://github.com/pixelglow/ZipZap/issues/105
end

target 'VOKEmbeddedTemplateToolsTests', :exclusive => true do
  pod "VOKEmbeddedTemplateTools", :path => "../"

  
end
